### PR TITLE
closes #77 #79 - raise error in red if 404, add units to temperature, and production steps parameter

### LINKED ISSUE #77: Check that PDB ID is valid - complete pdb_id_exists in from

### PR DESCRIPTION
**Pull request by MichaelShohat**

### CODE REVIEW

**Comment by MichaelShohat** [comment]
Tried adding field production_steps - #79 
received error after adding it to simulation_main_script - tuple has no attribute create_simulation.

**Comment by IlanitSmul** [comment]
@MichaelShohat 

In order to use a new field, you need to make the following changes:

- **forms.py:** Adds the field to the required class (`SimulationForm2_SimulationParameters`).
- **views.py**: Under the class `SimulationWizard`:
  * **`done`:** Adds the field as a parameter to the instance of the Simulation class.
  * **`clean_form_dict`:** Adds the following two lines:
       `production_steps = dict_.get('production_steps', '')`
        `clean_dict['production_steps'] = production_steps`
  * **`get_form_initial`:** Adds the field to the dictionary `step_2_prev_data`:
     ` 'production_steps': step_2_prev_data.get('2-production_steps')}`
- **simulation_main_script.py:** 
  * **`__init__`:**  Adds the field to the parameter list and adds the following line:
     `self.production_steps = float(production_steps)`.
  * **`create_simulation`:**  Use the new field.

**Comment by OrYasso** [comment]
This pull request **introduces 2 alerts** when merging 9dbbdd22a009332303f7583937abeb1d674dcdbb into d625d72d531bb2d687b2f40cf11099cf2fa4781d - [view on LGTM.com](https://lgtm.com/projects/g/TechnionYP5779/SimuMole/rev/pr-17819d51da68d2b77e0703d121cb1edcd9d71da7)

**new alerts:**

* 1 for Variable defined multiple times
* 1 for Wrong number of arguments in a class instantiation

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by MichaelShohat** [comment]
Do not merge this yet

**Comment by OrYasso** [comment]
This pull request **introduces 2 alerts** and **fixes 2** when merging 5d7251e1890ca0494e78405887d96485d5b4e4ed into d625d72d531bb2d687b2f40cf11099cf2fa4781d - [view on LGTM.com](https://lgtm.com/projects/g/TechnionYP5779/SimuMole/rev/pr-d96e2f76c6323d864293f7d0b5091b12c937d651)

**new alerts:**

* 1 for Syntax error
* 1 for Variable defined multiple times

**fixed alerts:**

* 2 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request closed without merging**
